import chalk from 'chalk';
import * as fs from 'fs-extra';
import ignore from 'ignore';
import * as os from 'os';
import * as path from 'path';

export interface IndexIgnoreOptions {
  exclude: string[];
}

const commont = `/*
* Generated by cli, don't modify manually
*/`;
const space = `${os.EOL}${os.EOL}`;

type IndexGeneratorOptions = {
  force: boolean;
  js: boolean;
  ignore: string;
};

export class IndexGenerator {
  url: string;
  isforce: boolean;
  isModule: boolean;
  isJs: boolean;
  ignore: IndexIgnoreOptions;

  ig = ignore();

  constructor(target: string, options: IndexGeneratorOptions) {
    this.url = target;
    this.isforce = options.force;
    this.isJs = options.js;

    if (fs.existsSync(options.ignore)) {
      this.ignore = require(options.ignore);

      this.ig.add(this.ignore.exclude);
    }
  }

  createFile(dirUrl?: string) {
    if (!dirUrl) {
      dirUrl = this.url;
    }
    const filePaths = fs.readdirSync(dirUrl);

    const exportContentObj = new Set();
    const importContentObj = new Set();

    let hasDirFile = false;

    const ext = this.isJs ? 'js' : 'ts';

    const targetUrl = path.join(dirUrl, `index.${ext}`);

    const dirName = path.basename(dirUrl);

    let exportCount = 0;
    filePaths.forEach(filePath => {
      const absoluteFilePath = path.join(dirUrl, filePath);

      if (this.checkPathVariable(absoluteFilePath)) {
        return 0;
      }

      const status = fs.statSync(absoluteFilePath);
      const isDir = status.isDirectory();

      let currentDirCount = 0;

      // check the folder is scss, if right skip the folder
      if (filePath === 'scss') {
        console.log('stop');
      }

      // check is dir
      if (isDir) {
        currentDirCount = this.createFile(absoluteFilePath);
        exportCount += currentDirCount;
      } else {
        if (
          !new RegExp(`\.${ext}$`, 'gi').test(filePath) ||
          new RegExp(`\.spec\.${ext}$`, 'gi').test(filePath) ||
          new RegExp(`^_`, 'gi').test(filePath) ||
          new RegExp(`\.test\.${ext}$`, 'gi').test(filePath) ||
          (!this.isJs && new RegExp(`^index\.${ext}$`, 'gi').test(filePath)) ||
          (!this.isModule && new RegExp(`\.module\.${ext}$`, 'gi').test(filePath))
        ) {
          return;
        }
        filePath = filePath.replace(new RegExp(`\.${ext}$`, 'gi'), '');
        if (filePath === 'index') {

          const template = fs.readFileSync(absoluteFilePath).toString();

          // if there has index and the index has content, create an file with current dir and
          if (!template.includes(commont)) {
            const dirTargetUrl = path.join(dirUrl, `${dirName}.js`);
            if (!fs.existsSync(dirTargetUrl)) {
              fs.writeFileSync(dirTargetUrl, template);
              console.log(`${chalk.yellow('rename file: ')} ${absoluteFilePath} => ${dirTargetUrl}`);
            }
            exportCount++;
            importContentObj.add(`import ${dirName} from './${dirName}';`);
            hasDirFile = true;
          }
          return;
        }
      }

      if (this.isJs) {
        if (!isDir) {
          const content = fs.readFileSync(absoluteFilePath).toString();
          if (content) {
            if (content.includes('export default')) {

              if (filePath === dirName) {
                importContentObj.add(`import ${filePath} from './${filePath}';`);
                hasDirFile = true;
              } else {
                exportContentObj.add(`export ${filePath} from './${filePath}';`);
              }
            } else {
              exportContentObj.add(`export * from './${filePath}';`);
            }
            exportCount++;
          }
        } else if (currentDirCount > 0) {
          exportContentObj.add(`export ${filePath} from './${filePath}';`);
          exportCount++;
        }
      } else {
        exportContentObj.add(`export * from './${filePath}';`);
        exportCount++;
      }
    });

    if (exportCount > 0) {
      if (fs.existsSync(targetUrl)) {
        if (!this.isforce) {
          console.log(`${chalk.red('existed ')} ${targetUrl}`);
          return;
        }
        console.log(`${chalk.yellow('update ')} ${targetUrl}`);
      } else {
        console.log(`${chalk.green('create ')} ${targetUrl}`);
      }


      fs.writeFileSync(targetUrl,
        commont + os.EOL +
        [...importContentObj].join(os.EOL) +
        (importContentObj.size > 0 ? space : '') +
        [...exportContentObj].join(os.EOL) +
        (exportContentObj.size > 0 ? (hasDirFile ? space : os.EOL) : '') +
        (hasDirFile ? `export default ${dirName};${os.EOL}` : '')
      );
    }

    return exportCount;
  }


  private checkPathVariable(fileUrl: string) {
    let checkUrl = fileUrl;
    if (checkUrl[0] === '/') {
      checkUrl = checkUrl.substring(1);
    }
    return this.ignore &&
      (this.ignore.exclude && this.ig.ignores(path.join(checkUrl)));
  }
}

