import chalk from 'chalk';
import * as fs from 'fs-extra';

import ignore, { Ignore } from 'ignore';
import * as os from 'os';
import * as path from 'path';
import { IndexIgnoreOptions } from '../index.generator';

type IndexFileCheckInput = {
  filePath: string;
  dirPath: string;
  ignore: IndexIgnoreOptions;
  ig: Ignore,
  dirName: string;
  isJs: boolean;
};

const commont = `/*
* Generated by cli, don't modify manually
*/`;

export class IndexFileCheck {
  status: fs.Stats;
  isDir: boolean;
  ext: string;

  private absoluteFilePath: string;

  constructor(private input: IndexFileCheckInput) {
    this.absoluteFilePath = path.join(input.dirPath, input.filePath);

    this.status = fs.statSync(this.absoluteFilePath);
    this.isDir = this.status.isDirectory();
    this.ext = this.input.isJs ? 'js' : 'ts';
  }

  checkPathVariable() {
    let checkUrl = this.absoluteFilePath;
    if (checkUrl[0] === '/') {
      checkUrl = checkUrl.substring(1);
    }
    if (this.input.ignore &&
      (this.input.ignore.exclude && this.input.ig.ignores(path.join(checkUrl)))
    ) {
      return this;
    }
    throw 'pathNot right';
  }

  // check the folder is scss, if right skip the folder
  checkIsScssFolder() {
    if (this.input.filePath === 'scss') {
      throw 'this is scss folder, stop';
    }
    return this;
  }
}
